compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  zero_stage: 3
  offload_optimizer_device: none
  offload_param_device: none
  gradient_clipping: 1.0
  zero3_init_flag: true
  tensor_parallel:
    tensor_model_parallel_size: 4
  pipeline_parallel:
    pipeline_model_parallel_size: 1
  gradient_accumulation_steps: 1
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
use_cpu: false
